### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lapfelix**
NSMutabelDeepLink > DPLMutableDeepLink

### CODE REVIEW

**Comment by wessmith** [comment]
@lapfelix Great catch. Thanks!

**Comment by wessmith** [comment]
Hey, @lapfelix could you possibly sign our CLA ahead of getting this merged?

The CLA is an unfortunate necessity operating open source libraries as part of a company :smile: 

https://docs.google.com/forms/d/1WHFWnzz5OL8c9o49KgpgyERzQUQajX5p8_80YLCghds/viewform?usp=send_form

**Comment by lapfelix** [comment]
Sure ! I just did it

It's really weird to do this only for a readme edit, haha

**Comment by wessmith** [comment]
@lapfelix Thanks. I know, but hopefully you'll contribute more :smile:

**Pull request merged**
